### ISSUE TITLE
Duplicating core behaviour?

### ISSUE THREAD

**Issue by rwaldron** [brianchirls/popcorn-base#1]
Popcorn.js core already has event emitters for plugin track "start" and "end"...

``` js

$p.on( "trackstart", function( event ) {
   // fired when any track starts
   // the event object will tell you which one it was
});

$p.on( "trackend", function( event ) {
   // fired when any track starts
   // the event object will tell you which one it was
});

```

It would be trivial to add "tracksetup" and "trackteardown" events to the core to compliment these

**Comment by brianchirls** [comment]
Rick,

Thanks for pointing these out. I didn't know about those.

I don't see where it hurts to have the "on_" events here, and they serve a slightly different purpose, since they're applied to specific Popcorn track events, as opposed to the "trackstart" and "trackend" events, which appear to fire on *any_ event. So they both have their place.

I would be in favor of adding "tracksetup" and "trackteardown" events to the core, however, it's probably not a good idea to add "trackframe." While it could certainly be useful, I wouldn't want to encourage triggering on EVERY event, rather just the ones you really need.

**Comment by rwaldron** [comment]
I'll get a ticket filed for "tracksetup" and "trackteardown"
